name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository Clone
        uses: actions/checkout@v4
    
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: futsal-platform
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository Clone
        uses: actions/checkout@v4
        
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: futsal-platform
          path: .

      - name: Copy JAR to EC2 using SCP
        run: |
           scp -o StrictHostKeyChecking=no -i kickconnect-key.pem build/libs/kickConnect-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/kickConnect-0.0.1-SNAPSHOT.jar

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo pkill -f 'java -jar' || true
            sleep 3

            # 🔹 기존 프로세스 강제 종료
            PID=$(ps aux | grep 'java -jar' | grep -v grep | awk '{print $2}')
            if [ ! -z "$PID" ]; then
              echo "Killing process $PID"
              sudo kill -9 $PID
              sleep 3
            fi

            chmod +x /home/${{ secrets.SERVER_USER }}/kickConnect-0.0.1-SNAPSHOT.jar
            nohup java -jar /home/${{ secrets.SERVER_USER }}/kickConnect-0.0.1-SNAPSHOT.jar > /home/${{ secrets.SERVER_USER }}/app.log 2>&1 &

            sleep 2
            ps aux | grep 'java -jar'
