name: Deploy to EC2

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository Clone
        uses: actions/checkout@v4
    
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: futsal-platform
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: futsal-platform
          path: .

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo pkill -f 'java -jar' || true
            sleep 5
            ps aux | grep 'java -jar'
            mv futsal-platform.jar /home/${{ secrets.SERVER_USER }}/futsal-platform.jar
            chmod +x /home/${{ secrets.SERVER_USER }}/futsal-platform.jar
            nohup setsid java -jar /home/${{ secrets.SERVER_USER }}/futsal-platform.jar > app.log 2>&1 &
            sleep 2
            ps aux | grep 'java -jar'
